### ISSUE TITLE
Can not compile with OpenSSL 1.1

### ISSUE THREAD

**Issue by mooncoincore** [mooncoincore/wallet#1]
Hi,

Can not compile with OpenSSL 1.1

CXX crypto/libbitcoinconsensus_la-aes.lo
CXX crypto/libbitcoinconsensus_la-hmac_sha256.lo
CXX crypto/libbitcoinconsensus_la-hmac_sha512.lo
CXX crypto/libbitcoinconsensus_la-ripemd160.lo
CXX crypto/libbitcoinconsensus_la-scrypt.lo
CXX crypto/libbitcoinconsensus_la-sha1.lo
CXX crypto/libbitcoinconsensus_la-sha256.lo
CXX crypto/libbitcoinconsensus_la-sha512.lo
CC lyra2m/libbitcoinconsensus_la-Lyra2.lo
CC lyra2m/libbitcoinconsensus_la-Sponge.lo
CC balloon/libbitcoinconsensus_la-bitstream.lo
In file included from balloon/bitstream.c:21:0:
balloon/bitstream.h:35:18: error: field ‘ctx’ has incomplete type
EVP_CIPHER_CTX ctx;
^~~
Makefile:3737: recipe for target 'balloon/libbitcoinconsensus_la-bitstream.lo' failed
make[2]: *** [balloon/libbitcoinconsensus_la-bitstream.lo] Error 1

I think there will be more error after this one.

**Comment by mooncoincore** [comment]
Before compilation, set the compiling parameters:
PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig   CFLAGS+=" -I/usr/include/openssl-1.0"   LDFLAGS+=" -L/usr/lib/openssl-1.0 -lssl" ./configure --with-openssl

after that everything is fine if you follow the instructions README.md
